# Generated by Django 3.0.1 on 2020-05-13 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_img', models.ImageField(default='achievement', upload_to='achievements_img')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('vr/ar', 'VR/AR'), ('robots', 'Robots'), ('energy', 'Energy'), ('programming', 'Programming'), ('design', 'Design'), ('hitech', 'HiTech')], max_length=60)),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('short_descreption', models.CharField(max_length=80)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('news_img', models.ImageField(default='news.png', upload_to='news_img')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
