# Generated by Django 3.0.1 on 2020-05-13 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminsAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='short_descreption',
            new_name='short_description',
        ),
    ]
