# Generated by Django 3.0.1 on 2020-05-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsAPI', '0002_auto_20200513_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='short_description',
            field=models.CharField(max_length=150),
        ),
    ]
