# Generated by Django 3.0.1 on 2020-05-14 09:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminsAPI', '0003_auto_20200513_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievements',
            old_name='news_img',
            new_name='achievement_img',
        ),
        migrations.AddField(
            model_name='achievements',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='news',
            name='tag',
            field=models.CharField(choices=[('vr/ar', '#VR/AR'), ('robots', '#Robots'), ('energy', '#Energy'), ('programming', '#Programming'), ('design', '#Design'), ('hitech', '#HiTech')], max_length=60),
        ),
    ]
