# Generated by Django 3.0.1 on 2020-05-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsAPI', '0005_achievements_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='tag',
            field=models.CharField(choices=[('vr/ar', '#VR/AR'), ('robots', '#Robots'), ('energy', '#Energy'), ('it', '#IT'), ('design', '#Design'), ('hitech', '#HiTech')], max_length=60),
        ),
    ]
