# Generated by Django 3.0.1 on 2020-05-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admins',
            name='img',
            field=models.ImageField(default='admin.jpg', upload_to='admins_img'),
        ),
    ]
